# Generated by Django 4.2.7 on 2023-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=300)),
                ("data", models.CharField(max_length=300)),
                ("price", models.FloatField(default=-1)),
                ("image", models.CharField(max_length=300)),
            ],
        ),
    ]
